pipeline {
    agent any

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main', url: 'https://github.com/BanielChips/CEN4802c-MidtermRepository.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building Docker image...'
                    bat 'docker build -t my-maven-app -f JavaCalculator\\Dockerfile JavaCalculator'
                }
            }
        }

//         stage('Run Tests') {
//             steps {
//                 script {
//                     echo 'Running tests...'
//                     bat 'docker run --rm my-maven-app mvn test'
//                 }
//             }
//         }

        stage('Run Application') {
            steps {
                script {
                    echo 'Running application...'
                    bat 'docker run --rm -p 8081:8080 my-maven-app java -cp /usr/src/app JavaCalculator.MainClass'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Build and Run succeeded!'
        }
        failure {
            echo 'Build or Run failed.'
        }
    }
}

