pipeline {
    agent any

    stages {
        stage('Clone repository') {
            steps {
                // Pull the code from your version control system (e.g., Git)
                git branch: 'main', url: 'https://github.com/BanielChips/CEN4802c-MidtermRepository.git'
            }
        }

        stage('Compile') {
            steps {
                dir('JavaCalculator'){
                    // Navigate to the correct directory where pom.xml is located and compile
                    echo 'Compiling...'
                    // Run Maven command to compile the project in the workspace
                    bat 'mvn clean compile'
                }

            }
        }

        stage('Run') {
            steps {
                // Run the compiled Java program
                dir('JavaCalculator') {
                    bat 'mvn exec:java -Dexec.mainClass="JavaCalculator"'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Build and Run succeeded!'
        }
        failure {
            echo 'Build or Run failed.'
        }
    }
}
